Script started on 2017年03月07日 (週二) 07時52分24秒
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/home $[00m whoam1;pq[Kwd[K[K[K[K[Ki;pwd
pd2vm
/home/pd2vm/home
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/home $[00m git config-[K -l
user.email=iceskyripple@gmail.com
user.name=iceskyripple
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/home $[00m git clone http://gi thub.com/iceksy[K[K[Kskyripple/lab1.git
Cloning into 'lab1'...
remote: Counting objects: 3, done.[K
remote: Total 3 (delta 0), reused 3 (delta 0), pack-reused 0[K
Unpacking objects:  33% (1/3)   Unpacking objects:  66% (2/3)   Unpacking objects: 100% (3/3)   Unpacking objects: 100% (3/3), done.
Checking connectivity... done.
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/home $[00m ca[K[K
Script done on 2017年03月07日 (週二) 07時53分17秒
